name: Ensure Contributor Is Trusted to Run CI
# Used as a gate to prevent untrusted contributors from exfiltrating our github secrets via malicious PR.
# This workflow will be blocked until a maintainer clicks the "Approve workflow runs" button.
# Then the ci.yml workflow will be allowed to run with secrets (it waits for this workflow to run).
# It needs to be two steps, do not attempt to use pull_request_target in ci.yml as 
# that mode does not wait for "Approve workflow runs" to be clicked, secrets are leaked immediately.

# Learn more:
# - https://securitylab.github.com/resources/github-actions-preventing-pwn-requests/
# - https://dvc.org/blog/testing-external-contributions-using-github-actions-secrets/
# - https://docs.github.com/en/actions/how-tos/write-workflows/choose-what-workflows-do/use-secrets
# - https://github.blog/changelog/2025-11-07-actions-pull_request_target-and-environment-branch-protections-changes/
# - https://github.com/orgs/community/discussions/179107

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - labeled
      - unlabeled
    paths-ignore:
      - "packages/docs/**"

permissions:
  contents: read

jobs:
  gate:
    runs-on: ubuntu-latest
    steps:
      # no-op
      - run: "true"
